# Priority levels
PRIORITY_EMERGENCY = "EMERGENCY"
PRIORITY_HIGH = "HIGH"
PRIORITY_ROUTINE = "ROUTINE"

PRIORITY_LEVELS = {
    PRIORITY_EMERGENCY: 1,
    PRIORITY_HIGH: 2,
    PRIORITY_ROUTINE: 3,
}

# Referral status
STATUS_PENDING = "PENDING"
STATUS_ACCEPTED = "ACCEPTED"
STATUS_REJECTED = "REJECTED"
STATUS_AWAITING_CLARIFICATION = "AWAITING_CLARIFICATION"
STATUS_LOCATION_ASSIGNED = "LOCATION_ASSIGNED"
STATUS_PATIENT_NOTIFIED = "PATIENT_NOTIFIED"
STATUS_PATIENT_ARRIVED = "PATIENT_ARRIVED"
STATUS_UNDER_CONSULTATION = "UNDER_CONSULTATION"
STATUS_COMPLETED = "COMPLETED"
STATUS_CANCELLED = "CANCELLED"

# User roles
ROLE_STUDENT = "STUDENT"
ROLE_FACULTY = "FACULTY"
ROLE_PATIENT = "PATIENT"
ROLE_ADMIN = "ADMIN"

# Preparation status
PREP_NOT_STARTED = "NOT_STARTED"
PREP_IN_PROGRESS = "IN_PROGRESS"
PREP_COMPLETED = "COMPLETED"
